create table Movies ( -- MovieID, Title, Release, Location, Category, Studio)
    MovieID int identity(1,1),
    Title nchar(60) not null,
    Release int not null,
    Location nchar(10) not null,
    Category nchar(15) not null,
    Studio nchar(15) not null
);

delete from Movies
insert into Movies (Title, Release, Location, Category, Studio) 
values
--Loui movie list:
('Pirates of the Caribbean: Curse of the Black Pearl', 2003, 'Loui', 'Live Action', 'Disney'),
('Pirates of the Caribbean: Dead Mans Chest', 2006, 'Loui', 'Live Action', 'Disney'),
('Pirates of the Caribbean: On Stranger Tides', 2011, 'Loui', 'Live Action', 'Disney'),
('Narnia', 2005, 'Loui', 'Live Action', 'Disney'),
('Sådan Træner Du Din Drage', 2010, 'Loui', 'Animation', 'Dreamworks'),
('Sådan Træner Du Din Drage 2', 2014, 'Loui', 'Animation', 'Dreamworks'),
('Modig', 2012, 'Loui', 'Animation', 'Pixar'),
('Klokkeren fra Notre Dame', 1996, 'Loui', 'Animation', 'Disney'),
('Tarzan', 1999, 'Loui', 'Animation', 'Disney'),
('101 Dalmatinere 2', 2001, 'Loui', 'Animation', 'Disney'),
('To På Flugt', 2010, 'Loui', 'Animation', 'Disney'),
('Op', 2009, 'Loui', 'Animation', 'Pixar'),
('Bambi', 1942, 'Loui', 'Animation', 'Disney'),
('Prinsen af Egypten', 1998, 'Loui', 'Animation', 'Dreamworks'),
('Vejen Til El Dorado', 2000, 'Loui', 'Animation', 'Dreamworks'),
('Mulan', 1998, 'Loui', 'Animation', 'Disney'),
('Mulan 2', 2004, 'Loui', 'Animation', 'Disney'),

--kat movie list:
('Bambi', 1942, 'Kat', 'Animation', 'Disney'),
('Askepot', 1950, 'Kat', 'Animation', 'Disney'),
('Alice i Eventyland', 1951, 'Kat', 'Animation', 'Disney'),
('Peter pan', 1953, 'Kat', 'Animation', 'Disney'),
('Lady og Vagabonden', 1955, 'Kat', 'Animation', 'Disney'),
('Lady og Vagabonden 2', 2001, 'Kat', 'Animation', 'Disney'),
('Tornerose', 1959, 'Kat', 'Animation', 'Disney'),
('101 Dalmatinere', 1961, 'Kat', 'Animation', 'Disney'),
('Aristocats', 1970, 'Kat', 'Animation', 'Disney'),
('Bernard og Bianca', 1977, 'Kat', 'Animation', 'Disney'),
('Bernard og Bianca sos fra Australien', 1990, 'Kat', 'Animation', 'Disney'),
('Mads og Mikkel', 1981, 'Kat', 'Animation', 'Disney'),
('Oliver & Co', 1988, 'Kat', 'Animation', 'Disney'),
('Den lille Havfrue', 1989, 'Kat', 'Animation', 'Disney'),
('Aladdin', 1992, 'Kat', 'Animation', 'Disney'),
('Pocahontas', 1995, 'Kat', 'Animation', 'Disney'),
('Klokkeren fra Notre Dame', 1996, 'Kat', 'Animation', 'Disney'),
('Herkules', 1997, 'Kat', 'Animation', 'Disney'),
('Mulan', 1998, 'Kat', 'Animation', 'Disney'),
('Tarzan', 1999, 'Kat', 'Animation', 'Disney'),
('Kejserens Nye Flip', 2000, 'Kat', 'Animation', 'Disney'),
('Atlantis: Det Forsvundne Rige', 2001, 'Kat', 'Animation', 'Disney'),
('Skatteplaneten', 2002, 'Kat', 'Animation', 'Disney'),
('Bjørne Brødre', 2003, 'Kat', 'Animation', 'Disney'),
('Bolt', 2008, 'Kat', 'Animation', 'Disney'),
('Prinsessen og Frøen', 2009, 'Kat', 'Animation', 'Disney'),
('To På Flugt', 2010, 'Kat', 'Animation', 'Disney'),
('Vilde Rolf', 2012, 'Kat', 'Animation', 'Disney'),
('Zootropolis', 2016, 'Kat', 'Animation', 'Disney'),
('Modig', 2012, 'Kat', 'Animation', 'Pixar'),
('Sådan Træner Du Din Drage', 2010, 'Kat', 'Animation', 'Dreamworks'),
('Lilo og Stich 2', 2005, 'Kat', 'Animation', 'Disney'),
('Løvernes Konge', 1994, 'Kat', 'Animation', 'Disney'),
('Løvernes Konge 2', 1998, 'Kat', 'Animation', 'Disney'),
('Løvernes Konge 3', 2004, 'Kat', 'Animation', 'Disney'),
('Op', 2009, 'Kat', 'Animation', 'Pixar'),
('Frost', 2013, 'Kat', 'Animation', 'Disney'),
('Frost 2', 2019, 'Kat', 'Animation', 'Disney'),
('Taran og Den Magiske Gryde', 1985, 'Kat', 'Animation', 'Disney'),

--heidi movie list:
('Lilo & Stitch', 2002, 'Heidi', 'Animation', 'Disney'),
('Pocahontas', 1995, 'Heidi', 'Animation', 'Disney'),
('Prinsessen og Frøen', 2009, 'Heidi', 'Animation', 'Disney'),
('Inderst Inde', 2015, 'Heidi', 'Animation', 'Pixar'),
('Bjørne Brødre', 2003, 'Heidi', 'Animation', 'Disney'),
('Bjørne Brødre 2', 2006, 'Heidi', 'Animation', 'Disney'),
('Skønheden og Udyret', 2017, 'Heidi', 'Animation', 'Disney'),
('Klokkeren fra Notre Dame', 1996, 'Heidi', 'Animation', 'Disney'),
('Coco', 2017, 'Heidi', 'Animation', 'Pixar'),
('Skønheden og Udyret', 1991, 'Heidi', 'Animation', 'Disney'),
('Big Hero 6', 2014, 'Heidi', 'Animation', 'Disney'),
('Croods', 2013, 'Heidi', 'Animation', 'Dreamworks'),
('Madagascar', 2005, 'Heidi', 'Animation', 'Dreamworks'),
('Biler', 2006, 'Heidi', 'Animation', 'Pixar'),
('Skatteplaneten', 2002, 'Heidi', 'Animation', 'Disney'),
('Stor Ståhaj', 2004, 'Heidi', 'Animation', 'Dreamworks'),
('Sværdet i Stenen', 1963, 'Heidi', 'Animation', 'Disney'),
('Shrek', 2001, 'Heidi', 'Animation', 'Dreamworks'),
('Mary Poppins Returns', 2018, 'Heidi', 'Live Action', 'Disney'),

('101 Dalmatinere', 1961, 'Heidi', 'Animation', 'Disney'),
('Vilde Rolf', 2006, 'Heidi', 'Animation', 'Disney'),
('Peter Plys - Jagten på den forsvundne Jakob', 1997, 'Heidi', 'Animation', 'Disney'),
('Dumbo', 1941, 'Heidi', 'Animation', 'Disney'),
('Monsters mod Aliens', 2009, 'Heidi', 'Animation', 'Dreamworks'),
('Shreklig Jul', 2007, 'Heidi', 'Animation', 'Dreamworks'),
('Sådan træner du din drage', 2010, 'Heidi', 'Animation', 'Dreamworks'),
('Alice i Eventyrland', 1951, 'Heidi', 'Live Action', 'Disney'),
('De Utrolige', 2004, 'Heidi', 'Animation', 'Pixar'),
('Oliver & Co', 1988, 'Heidi', 'Animation', 'Disney'),
('De Frygtløse - The Muuhvie', 2004, 'Heidi', 'Animation', 'Disney'),
('Monsters, Inc.', 2001, 'Heidi', 'Animation', 'Pixar'),
('Kejserens Nye Flip', 2000, 'Heidi', 'Animation', 'Disney'),
('Askepot II - Drømmen bliver til virkelighed', 2002, 'Heidi', 'Animation', 'Disney'),
('Snehvide og de syv små dværge', 1937, 'Heidi', 'Animation', 'Disney'),
('Ratatouille', 2007, 'Heidi', 'Animation', 'Pixar'),
('Mads og Mikkel', 1981, 'Heidi', 'Animation', 'Disney'),
('Herkules', 1997, 'Heidi', 'Animation', 'Disney'); 
--
select * from Movies
order by Title Asc;
